[FileDialog]
history=file:///home/kira/[English Translated] Death Note, file:///home/kira/Death Note - Specials, file:///home/kira, file:///home/kira/Calibre Library, file:///home/kira/Calibre Library/Boredom [2005]/[English Translated] Death Note - Volume 01 (29)
lastVisited=file:///home/kira
qtVersion=6.6.2
shortcuts=file:///home/kira, file:
sidebarWidth=83
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x3\f\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1\xe5\0\0\0\x1\0\0\0\0\0\0\0\x8c\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0\x62\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0)
viewMode=Detail
